// <auto-generated />
using GuitarShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuitarShop.Migrations
{
    [DbContext(typeof(ContextCoordinates))]
    [Migration("20230904212944_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuitarShop.Models.CellCoordinates", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CellCoordinates");

                    b.HasData(
                        new
                        {
                            ID = "11",
                            color = "blue"
                        },
                        new
                        {
                            ID = "12",
                            color = "blue"
                        },
                        new
                        {
                            ID = "13",
                            color = "blue"
                        },
                        new
                        {
                            ID = "21",
                            color = "blue"
                        },
                        new
                        {
                            ID = "22",
                            color = "blue"
                        },
                        new
                        {
                            ID = "23",
                            color = "blue"
                        },
                        new
                        {
                            ID = "31",
                            color = "blue"
                        },
                        new
                        {
                            ID = "32",
                            color = "blue"
                        },
                        new
                        {
                            ID = "33",
                            color = "blue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
